# Generated by Django 4.2 on 2023-11-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_category_product_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'File', 'verbose_name_plural': 'fils'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='file',
            table='files',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
